image: Visual Studio 2015
stack: node 19
branches: 
  only:
    - master
cache: node_modules
install:
  - ps: Install-Product node $env:nodejs_version
  - npm install
build: off
test_script:
  - npm run lint && npm test